- defaults:
    link: 
      create: true
      relink: true

- clean: ['~']

- link:
    # ~/.bash:
    # ~/.bash_profile:
    ~/.bashrc: bashrc
    # ~/dotfiles: ''
    ~/.vim: vim
    ~/.gitconfig: gitconfig
    ~/powerline-shell.py: powerline-shell/powerline-shell.py

- shell:
  - [git submodule update --init --recursive, Installing submodules]
